-- 경기도에 위치한 식품창고 목록 출력하기
-- NULL일 경우 특정 값을 변경하는 것은 IFNULL을 사용하면 된다.
SELECT WAREHOUSE_ID, WAREHOUSE_NAME, ADDRESS, IFNULL(FREEZER_YN, 'N') AS FREEZER_YN FROM FOOD_WAREHOUSE WHERE ADDRESS LIKE '경기도%' ORDER BY WAREHOUSE_ID ASC;
