-- 조건에 맞는 도서 리스트 출력하기
-- 출력 결과와 동일하게 날짜 포맷을 맞춰야함에 유의
SELECT BOOK_ID, DATE_FORMAT(PUBLISHED_DATE, '%Y-%m-%d') AS PUBLISHED_DATE
FROM BOOK
WHERE CATEGORY = '인문' AND DATE_FORMAT(PUBLISHED_DATE, '%Y') = 2021
ORDER BY PUBLISHED_DATE ASC;
