-- 대여 기록이 존재하는 자동차 리스트 구하기
SELECT crcc.CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY crcrh1
INNER JOIN CAR_RENTAL_COMPANY_CAR crcc
ON crcrh1.CAR_ID = crcc.CAR_ID
WHERE crcrh1.START_DATE LIKE '%-10-%' AND INSTR(crcc.CAR_TYPE, '세단')
GROUP BY crcc.CAR_ID
ORDER BY crcrh1.CAR_ID DESC;