-- 없어진 기록 찾기
-- ANIMAL_INS에는 없지만, ANIMAL_OUTS에는 있는 데이터를 조회해야하므로
-- ANIMAL_OUTS를 기준으로 전부 출력하되, ANIMAL_INS의 ANIMAL_ID가 NULL이어야 하므로 RIGHT JOIN을 사용하였다.

SELECT ao.ANIMAL_ID, ao.NAME
FROM ANIMAL_INS ai
RIGHT JOIN ANIMAL_OUTS ao
ON ai.ANIMAL_ID = ao.ANIMAL_ID
WHERE ai.ANIMAL_ID IS NULL
ORDER BY ao.ANIMAL_ID ASC, ao.NAME ASC;
