-- 자동차 대여 기록에서 대여중 / 대여 가능 여부 구분하기
SELECT car_his1.CAR_ID, IF(car_his2.CAR_ID IS NULL, '대여 가능', '대여중') AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS car_his1
LEFT JOIN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE (DATE('2022-10-16') BETWEEN START_DATE AND END_DATE)
) AS car_his2
ON car_his1.CAR_ID = car_his2.CAR_ID
GROUP BY car_his1.CAR_ID
ORDER BY car_his1.CAR_ID DESC;