-- 조건에 맞는 사용자 정보 조회하기
SELECT UGU.USER_ID, UGU.NICKNAME,
CONCAT(UGU.CITY, " ", UGU.STREET_ADDRESS1, " ", UGU.STREET_ADDRESS2) AS "전체주소",
CONCAT(SUBSTR(UGU.TLNO, 1, 3), "-", SUBSTR(UGU.TLNO, 4, 4), "-", SUBSTR(UGU.TLNO, 8)) AS "전화번호"
FROM USED_GOODS_BOARD UGB
JOIN USED_GOODS_USER UGU
ON UGB.WRITER_ID = UGU.USER_ID
GROUP BY UGB.WRITER_ID
HAVING COUNT(UGB.WRITER_ID) >= 3
ORDER BY UGU.USER_ID DESC;