-- 조건에 맞는 사용자와 총 거래금액 조회하기
SELECT ugu.USER_ID, ugu.NICKNAME, SUM(PRICE) AS 'TOTAL_SALES'
FROM USED_GOODS_BOARD ugb
INNER JOIN (
    SELECT USER_ID, NICKNAME
    FROM USED_GOODS_USER) ugu
ON ugb.WRITER_ID = ugu.USER_ID
WHERE ugb.STATUS = 'DONE'
GROUP BY ugb.WRITER_ID
HAVING SUM(PRICE) >= 700000
ORDER BY TOTAL_SALES;