-- 조회수가 가장 많은 중고거래 게시판의 첨부파일 조회하기
SELECT CONCAT("/home/grep/src/", UGF.BOARD_ID, "/", UGF.FILE_ID, UGF.FILE_NAME, UGF.FILE_EXT)
AS FILE_PATH
FROM USED_GOODS_BOARD UGB1
JOIN USED_GOODS_FILE UGF
ON UGB1.BOARD_ID = UGF.BOARD_ID
WHERE UGB1.VIEWS = (SELECT MAX(USED_GOODS_BOARD.VIEWS)
                    FROM USED_GOODS_BOARD)
ORDER BY UGF.FILE_ID DESC;