-- 5월 식품들의 총매출 조회하기
SELECT fd.PRODUCT_ID, fd.PRODUCT_NAME, (fd.PRICE * fo.AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT fd
INNER JOIN (SELECT PRODUCT_ID, SUM(AMOUNT) AS AMOUNT
            FROM FOOD_ORDER
            WHERE DATE_FORMAT(PRODUCE_DATE, '%Y-%m') = '2022-05'
            GROUP BY PRODUCT_ID) fo
ON fd.PRODUCT_ID = fo.PRODUCT_ID
ORDER BY (fd.PRICE * fo.AMOUNT) DESC, fd.PRODUCT_ID ASC;
