-- 저자 별 카테고리 별 매출액 집계하기
SELECT auth.AUTHOR_ID, auth.AUTHOR_NAME, bk.CATEGORY, SUM(bk.PRICE * bs.SALES) AS TOTAL_SALES
FROM BOOK_SALES bs
JOIN BOOK bk
    ON bk.BOOK_ID = bs.BOOK_ID
JOIN AUTHOR auth
    ON bk.AUTHOR_ID = auth.AUTHOR_ID
WHERE DATE(bs.SALES_DATE) BETWEEN '2022-01-01' AND '2022-01-31'
GROUP BY auth.AUTHOR_NAME, bk.CATEGORY
ORDER BY auth.AUTHOR_ID ASC, bk.CATEGORY DESC;